using Microsoft.EntityFrameworkCore;

namespace BackyardGleanersApi.Models
{
  public class BackyardGleanersApiContext : DbContext
  {
    public DbSet<Gardener> Gardeners { get; set; }
    public BackyardGleanersApiContext(DbContextOptions<BackyardGleanersApiContext> options) : base(options)
    {
    }
    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<Gardener>()
        .HasData(
          new Gardener { GardenerId = 1, Name = "Eusebie and Kate", 
          Description = "", 
          Food = "Tomatoes", 
          Availability = "", 
          Location = "N Squash St & N Lombard Ave, Portland, OR 97217", 
          Contact = "siebubal@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 2, Name = "Cherry Bark", 
          Description = "", 
          Food = "Cherries", 
          Availability = "",
          Location = "N Macrum Ave & N Lombard St, Portland, OR 97203", 
          Contact = "Cb@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 3, Name = "Priscilla Plum", 
          Description = "", 
          Food = "Italian Plums", 
          Availability = "", 
          Location = "NW 19th Ave & NW Johnson St, Portland, OR 97209", 
          Contact = "prp@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 4, Name = "Zack and Inna Thompson", 
          Description = "", 
          Food = "Zucchinis", 
          Availability = "", 
          Location = "SE 9th Ave & SE Division StPortland, OR 97214", 
          Contact = "zuch@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 5, Name = "Granny Smith", 
          Description = "", 
          Food = "Apples", 
          Availability = "", 
          Location = "NE 33rd Ave & NE Killingsworth StPortland, OR 97211", 
          Contact = "gs@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 6, Name = "Berry Sweetwater", 
          Description = "", 
          Food = "Strawberries", 
          Availability = "", 
          Location = "SW Condor Ave & SW Barbur BlvdPortland, OR 97239", 
          Contact = "bbsweet@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 7, Name = "Padma Periwinkle", 
          Description = "", 
          Food = "Persimmons", 
          Availability = "", 
          Location = "NE 24th Ave & Northeast Broadway, Portland, OR 97232", 
          Contact = "peri@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 8, Name = "Hazel Folgelstein", 
          Description = "", 
          Food = "Hazelnuts", 
          Availability = "", 
          Location = "Northwest Skyline Boulevard & Northwest Cornell Road, Forest Park, Portland, OR 97229", 
          Contact = "hazel@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 9, Name = "Carrie Cuke", 
          Description = "", 
          Food = "Cucumbers", 
          Availability = "", 
          Location = "North Mason Street & North Castle Avenue, Portland, OR 97227", 
          Contact = "cc@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 10, Name = "Ronnie Romulus", 
          Description = "", 
          Food = "Romaine Lettuce", 
          Availability = "", 
          Location = "North Morgan Street & North Moore Avenue, Portland, OR 97217", 
          Contact = "rom@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 11, Name = "Kaley Green", 
          Description = "", 
          Food = "Kale", 
          Availability = "", 
          Location = "SE Duke St & SE 66th AvePortland, OR 97206", 
          Contact = "kaleyg@gmail.com", 
          ProfilePic = "" },
          new Gardener { GardenerId = 12, Name = "Bill Bloom", 
          Description = "", 
          Food = "Blueberries", 
          Availability = "", 
          Location = "Northeast Wygant Street & Northeast 10th Avenue, Portland, OR 97211", 
          Contact = "bloom@gmail.com", 
          ProfilePic = "" }
        );
    }
  }
}